#!/bin/bash

set -e

UINTENT_ROOT=$(pwd)
UINTENT_SDK_DIR="$UINTENT_ROOT/$UINTENT_OPENWRT_DIR/sdk-$UINTENT_PRITARGET-$UINTENT_SUBTARGET-$OPENWRT_VERSION"
UINTENT_IMAGEBUILDER_DIR="$UINTENT_ROOT/$UINTENT_OPENWRT_DIR/imagebuilder-$UINTENT_PRITARGET-$UINTENT_SUBTARGET-$OPENWRT_VERSION"

REPO_FILE="$UINTENT_IMAGEBUILDER_DIR/repositories.conf"

REPOS_HEAD="$(cat "$REPO_FILE" | head -1)"

UINTENT_REPO_PREFIX="# UINTENT_PREFIX"

if [ "$UINTENT_REPO_PREFIX" = "$REPOS_HEAD" ]; then
    exit 0
fi

PKG_ARCH="$(ls "$UINTENT_SDK_DIR/bin/packages")"

echo "$UINTENT_REPO_PREFIX" > "$REPO_FILE.new"
echo "src/gz uintent file://$UINTENT_SDK_DIR/bin/packages/$PKG_ARCH/uintent" >> "$REPO_FILE.new"
cat "$REPO_FILE" >> "$REPO_FILE.new"
mv "$REPO_FILE.new" "$REPO_FILE"
